os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ 
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: thijS+/Fb4bK4wIXjkDWA43pZ4Hv3jDHkrrVp9cUgSLMIy2V8SiNMgGuRv+cL19ilzZA3Z4SiCIDF1GuGvrcqU2L0McOALL8lS+RhREf+5ZmZ+X1+3+tzK4COpr2qZ8t+zQ9JmYC6BZzbdgCSLc5Enios7sTaWsNIk2LKKXaBix9SLEt+Bu2x6sbp9GbwwRNE5sendtBczOsm2h7cvJLAhBIuvj9tQeGJwsqSaqxaMAMwRNbtFKF5lR3PxtC1Cj3f/7+nFkSTA7cYcOByqKnPLFcKumrZ6vxRhjgk6kg33mfbqPEpFXdpV18qMr01ZD0Wc11EzWLQ869kN6vq6gixnmMlkHoAPBmZfCRmtrT4KpQu8i7VSwtxiR4MAh9mbgL3vRFvgZ2kvOxuVSxdeNxrJlmQ64zRGf3jd1/Gl5C+7tQKNjxMg5f++cVSR0iPuPtjIs7AtHkNCi7a+jnPzpEX0Y2/ESEEzMvBk01yVqZakRiwUt4U7AsmcD/Bw9tWjmIW10xpw1b3thuYZiHhDZLpLJR1Jhb5Jaoq0dgxad/6I+LJYWgEgO/5M5sRqYVMj7pGjzkOL31nCEqrQSjxmrSdQrc5AdaPFAw0UITFo4UrM/c8H0lSejjRksxH295HKFmWTgfoJECeCypw4oLWYn3mN4WWPHsxMcRzrc+vhB4XqU=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=org.molgenis:molgenis-app-capice
before_deploy:
  - export WAR=$(ls molgenis-app-capice/target/molgenis-app-capice-*.war)
deploy:
  provider: releases
  token:
    secure: Ehya6FgMmDCcntenKsKfn26HPfLceFv/2XnHg2SbGD2+x3RVwmQdswkRjBfKTDtK+ZmlYorfUug5gVY9ScES/zbTZMOilG3sZbzB/XEDwxsusJ0DjPBGk7Y6LDE85FBsAjMBC6nV1CGpj+Q3Oz7U1bJK58I1RL5ygZwBeGiwDhC3wbfo7SzHHR+exaIaKGQcOflRUEOuJIt7hWOMFGHKUX1zR+HrtoBZ2PriY60u1e6GxnZStMPVUaBjwVWvA+0YB+1f/ZLyzJaK37Tf10YxX5RyHZkzrHm9+B9eRxbieE0VueHm33EwIA7+5aBAh01rsPxWJsjOXydssHEMNlfwYMljvASiMPq1Xr8NaEOMP7CVOvL9iBc7xe1BoMCOZ2dWw3mJva1M4fHx+z/QZFI2Ck2ESZ4N0UnrC7X9rLdSscI3D5x4oVnsFPpx1XNv5OUSLSanQFZ9rNjOzB+uLZr4y6abxvXu6Ta4vFi2nqqQuXkBIAdi4x6mN555D8qHWzWasfyG6HIwL0nx9l/qwNBdx1FYAiekk8EFVPD+OqXw86db1But9rQwy4C9Z+QR0fFGnw60pFjqOZyEj0ctpWJJ0DF6c1jvRQHzLqPMbjTFoziHrj8KStvAJGIx27j1E1b3ZQyKC/u1wfyrIsOP1EEVzfjq2mYQxcKsfroxaY37waE=
  file: "${WAR}"
  prerelease: true
  on:
    tags: true
    condition: ${TRAVIS_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
  edge: true # opt in to dpl v2
